# Generated by Django 2.2 on 2019-09-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(verbose_name='start time and date')),
                ('end_time', models.DateTimeField(verbose_name='end time and date')),
                ('categories', models.ManyToManyField(to='eventFinderApp.Category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='events',
            field=models.ManyToManyField(to='eventFinderApp.Event'),
        ),
    ]
